# Generated by Django 5.0.6 on 2024-07-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0002_gazeteci_alter_makale_yazar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='makale',
            name='kategori',
            field=models.ManyToManyField(related_name='makaleler', to='haberler.kategori'),
        ),
    ]
