# Generated by Django 5.0.6 on 2024-07-02 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0003_kategori_makale_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=50)),
                ('metin', models.TextField()),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='haberler.makale')),
            ],
        ),
    ]
